I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 22, in script
    e "Вы создали новую игру Ren'Py."
Exception: Sayer 'e' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 22, in script
    e "Вы создали новую игру Ren'Py."
  File "C:\renpy-7.3.5-sdk\renpy\ast.py", line 678, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\renpy-7.3.5-sdk\renpy\ast.py", line 576, in eval_who
    raise Exception("Sayer '%s' is not defined." % who.encode("utf-8"))
Exception: Sayer 'e' is not defined.

Windows-8-6.2.9200
Ren'Py 7.3.5.606
Blue Ticket 1.0
Thu Nov 26 23:21:10 2020
